Add object-bound/proxy similar to object-bound/property but better
This only works with ES6 Proxy, which is currently only available
in Firefox and Microsoft Edge.

This implementation is better, because object-bound/property
only works for enumerable properties and won't work for native
objects, like String in the following example:

// doesn't work with object-bound/property
var str = 'Hello!';
var up = str.bound.toUpperCase; // undefined
up(); // Uncaught TypeError: up is not a function

// works with object-bound/proxy
var str = 'Hello!';
var up = str.bound.toUpperCase; // function toUpperCase()
up(); // 'HELLO!'